### PR TITLE
Fix compilation on Mac OS X

### PR DESCRIPTION
**Pull request by ghost**
A couple quick fixes to make `libxmljs-mt` work on Mac OS X.

In `vendor/libxml/include/libxml/xmlversion.h`, LIBXML_THREAD_ENABLED is only enabled if there's an appropriate "I want threads" macro defined. None of the appropriate macros appear to be defined by default on OS X, so define `_REENTRANT` explicitly in libxml.gyp.

In threads.c: PTHREAD_ONCE_INIT is a static initializer according the the POSIX threads specification, but happens to be `0` on glibc so you can get away with using it outside of a static initialization context. It expands to `{_PTHREAD_ONCE_SIG_init, {0}}` on OS X, hence the error.

There may be prettier ways to do one or both of these, but the fixes appear to work on this 10.9.5 machine, and the test suite passes. Currently untested on 10.10, but I suspect @alxndrsn will be able to give this a test on that platform shortly.

### CODE REVIEW

**Comment by gagern** [comment]
Thanks for reporting this. I'd like to have a closer look at how libxml itself deals with these issues, e.g. using [MacPorts](https://trac.macports.org/browser/trunk/dports/textproc/libxml2/Portfile) or [Homebrew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libxml2.rb). I'd prefer duplicating those approaches, and avoid modifying the vendor code base if possible.

**Comment by gagern** [comment]
Explicitely setting `_REENTRANT` is consistent with [current upstream `configure.ac`](https://github.com/GNOME/libxml2/blob/974db365de3a3d78a6cd7f5871f05e1432bab9b5/configure.ac#L1091). The `PTHREAD_ONCE_INIT` issue is addressed upstream by https://github.com/GNOME/libxml2/commit/3f6cfbd1d38d0634a2ddcb9a0a13e1b5a2195a5e. I'll upgrade to libxsml 2.9.2 to include that fix, and merge your pull request for its `_REENTRANT` part.

**Comment by ghost** [comment]
Sounds good, thanks so much for looking in to it.

**Comment by gagern** [comment]
You can give my current master (0cecc547969abc213877294a3f1c2ea047440476) a try, see whether that works for you. It's now using a submodule for the upstream code, so don't forget to run `git submodule update --init` if you build manually from a git checkout. I get some strange build errors on Travis for io.js which I'll need to investigate, but the situation on OS X for node.js should be improved. Let me know if you experience any other problems.

**Pull request closed without merging**
